# Generated by Django 3.2.12 on 2023-07-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_municipio', models.CharField(max_length=20)),
                ('ide_municipio', models.IntegerField()),
                ('ide_pais', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
    ]
