# Generated by Django 3.2.12 on 2023-07-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0002_auto_20230716_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Especial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ide_area_especial', models.IntegerField()),
                ('cod_area_especial', models.IntegerField()),
                ('nom_area_especial', models.IntegerField()),
            ],
            options={
                'db_table': 'area_especial',
            },
        ),
    ]
