# Generated by Django 3.2.12 on 2023-07-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0003_area_especial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Especial_Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ide_area_especial', models.IntegerField()),
                ('ide_municipio', models.IntegerField()),
            ],
            options={
                'db_table': 'area_especial_municipio',
            },
        ),
    ]
