# Generated by Django 3.2.12 on 2023-07-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0004_area_especial_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cisternas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_beneficiario', models.CharField(max_length=100)),
                ('cpf_beneficiario', models.CharField(max_length=11)),
                ('nis_beneficiario', models.CharField(max_length=12)),
                ('tip_executor', models.CharField(max_length=20)),
                ('cod_implementacao', models.IntegerField()),
                ('nom_comunidade', models.CharField(max_length=50)),
                ('nom_convenio', models.CharField(max_length=20)),
                ('tip_situacao', models.CharField(max_length=50)),
                ('dat_inicio_construcao', models.DateField()),
                ('dat_fim_construcao', models.DateField()),
                ('tip_aprovacao', models.CharField(max_length=20)),
                ('dat_aprovacao', models.DateField()),
            ],
            options={
                'db_table': 'cisternas',
            },
        ),
        migrations.AlterField(
            model_name='municipio',
            name='des_status',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
