# Generated by Django 3.2.12 on 2023-07-24 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0006_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
