# Generated by Django 3.2.12 on 2023-07-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0007_delete_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cisternas',
            name='ide_municipio',
            field=models.IntegerField(default=0),
        ),
    ]
