# Generated by Django 3.2.12 on 2023-07-27 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0008_cisternas_ide_municipio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cisternas',
            options={'managed': False},
        ),
    ]
