# Generated by Django 3.2.12 on 2023-07-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0009_alter_cisternas_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_ano', models.IntegerField()),
                ('dat_mes', models.IntegerField()),
                ('cpf_produtor', models.IntegerField()),
                ('ide_municipio', models.IntegerField()),
                ('ide_alimento', models.IntegerField()),
                ('qtd_alimento', models.FloatField()),
                ('val_alimento', models.FloatField()),
                ('des_tipo_alimento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'alimentos',
            },
        ),
        migrations.CreateModel(
            name='TipoAlimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_tipo_alimento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipoalimento',
            },
        ),
    ]
