# Generated by Django 3.2.12 on 2023-08-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0013_entregasleite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregasleite',
            name='ide_tipo_leite',
            field=models.IntegerField(),
        ),
    ]
