# Generated by Django 3.2.12 on 2023-08-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlte3', '0014_alter_entregasleite_ide_tipo_leite'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregasleite',
            name='des_status',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
